// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHShjdbyjbSjMHr5DP2wDn1fa0sF3oHo',
    appId: '1:915034731337:web:dcdbee5c0aba18b238a098',
    messagingSenderId: '915034731337',
    projectId: 'flutter-notification-11727',
    authDomain: 'flutter-notification-11727.firebaseapp.com',
    storageBucket: 'flutter-notification-11727.appspot.com',
    measurementId: 'G-HSP1EDFDFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjk4FJ6Oim8VGnmUGK8KubZTOhfCjwMDc',
    appId: '1:915034731337:android:83c46931581613f638a098',
    messagingSenderId: '915034731337',
    projectId: 'flutter-notification-11727',
    storageBucket: 'flutter-notification-11727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8Ow_OcOX6hD1B-VyKhXBd2Y8785-cF4',
    appId: '1:915034731337:ios:081f2de54ad1582638a098',
    messagingSenderId: '915034731337',
    projectId: 'flutter-notification-11727',
    storageBucket: 'flutter-notification-11727.appspot.com',
    iosClientId: '915034731337-c6cbvpig0t374ingst1fpabu2pm6anfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8Ow_OcOX6hD1B-VyKhXBd2Y8785-cF4',
    appId: '1:915034731337:ios:69ccdd785ffea44538a098',
    messagingSenderId: '915034731337',
    projectId: 'flutter-notification-11727',
    storageBucket: 'flutter-notification-11727.appspot.com',
    iosClientId: '915034731337-kpac50v0rri487h5uu7o9au5hnumh79f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
